### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mallman** [ActuallyTaylor/SFSymbols#3]
I want to include SFSymbols in my (as yet unreleased) iOS app, but I need your permission. 👍

Can you assign a license to this project so I can give proper attribution?

Cheers.

**Comment by ActuallyTaylor** [comment]
I just added a license in c583b2a! Sorry about that, and good luck with your app!

**Comment by mallman** [comment]
> I just added a license in [c583b2a](https://github.com/ActuallyTaylor/SFSymbols/commit/c583b2a02bd0353c2a3d745d0cfe9fd1562df3e8)! Sorry about that, and good luck with your app!

Thank you and thank you.
