### ISSUE TITLE
Incorrect macOS version availability for some symbols

### ISSUE THREAD

**Issue by mallman** [ActuallyTaylor/SFSymbols#5]
I was trying to use `righttriangle_split_diagonal` in my macOS SwiftUI app and the compiler is telling me it's only availably on macOS 15 or newer. According to the SF Symbols app, it should be available starting from macOS 14.

I noticed the same is true of several other symbols. I suspect that these symbols are available from macOS 14, not 15.

**Comment by ActuallyTaylor** [comment]
I will get on this!

**Comment by mallman** [comment]
Would you mind cutting a new release incorporating this fix?
